Feature/rad 131 migrate gradle docker to use GitHub actions instead of travis ci
brightsparklabs/gradle-docker pull request #10
Opened 2022-02-17 23:07 UTC by lewis-russell

2022-02-18 01:39 UTC, thomas-anderson-bsl requested changes
Few minor changes.
Essentially replicate the PR here please: https://github.com/brightsparklabs/gradle-docs/pull/7/files

2022-02-18 01:39 UTC, thomas-anderson-bsl commented on .github/workflows/gradle-docker-ci.yml
> +      if: github.ref == 'refs/heads/master'
I'd kind of prefer if we did test and publish in separate workflows so it's more clear what's happening.

2022-02-18 01:39 UTC, thomas-anderson-bsl commented on .github/workflows/gradle-docker-ci.yml
> +##
Could you please bump the `com.gradle.plugin-publish` version in `build.gradle`, and add the `maven-publish` plugin too please

We essentially want to mirror the changes that Ben has done in here: https://github.com/brightsparklabs/gradle-docs/pull/7/files

2022-02-18 01:39 UTC, thomas-anderson-bsl commented on .github/workflows/gradle-docker-ci.yml
> +        echo "gradle.publish.secret=${GRADLE_PUBLISH_SECRET}" >> ~/.gradle/gradle.properties
This way of referencing the GRADLE_PUBLISH_X variables won't work. See how to do it here: https://github.com/brightsparklabs/gradle-docs/pull/7/files

2022-02-23 01:31 UTC, closed without merging

2023-11-02 21:33 UTC, al-jeyapal commented
This is closed as the repo has been migrated to use the new actions already.